name: MonsterBattle
version: '1.0-SNAPSHOT'
main: de.thecoolcraft11.monsterBattle.MonsterBattle
api-version: '1.21'

commands:
  setphase:
    description: Set the game phase (lobby, farm, battle, end)
    usage: /setphase <lobby|farm|battle|end>
    permission: monsterbattle.setphase
  mobspawn:
    description: Manage arena monster spawn points
    usage: |-
      /mobspawn add <x> <y> <z>
      /mobspawn addhere
      /mobspawn addrel <dx> <dy> <dz>
      /mobspawn list
      /mobspawn remove <index>
      /mobspawn clear
    permission: monsterbattle.setphase
  dtp:
    description: Teleport a player to a world (dimension) and coordinates
    usage: /dtp <player> <world> <x> <y> <z>
    permission: monsterbattle.dtp
  worldname:
    description: Show the current world name (your own or another player's)
    usage: /worldname [player]
    permission: monsterbattle.worldname
  mobtp:
    description: Teleport to a remaining tracked arena mob for your team (battle phase)
    usage: |-
      /mobtp [nearest|random|list]
    permission: monsterbattle.mobtp
  capturedmobs:
    description: View captured mobs summary for your team or another team
    usage: /capturedmobs [team]
    permission: monsterbattle.captured.view

permissions:
  monsterbattle.setphase:
    description: Allows changing the game phase
    default: op
  monsterbattle.notify:
    description: Receive broadcast messages about phase changes
    default: true
  monsterbattle.dtp:
    description: Allows using /dtp to teleport players between dimensions
    default: op
  monsterbattle.worldname:
    description: Allows using /worldname
    default: true
  monsterbattle.mobtp:
    description: Allows using /mobtp to teleport to tracked arena mobs
    default: true
  monsterbattle.captured.view:
    description: Allows viewing your own team's captured mobs
    default: true
  monsterbattle.captured.others:
    description: Allows viewing other teams' captured mobs
    default: op
  monsterbattle.captured.summary:
    description: Allows viewing summary of captured mobs for all teams
    default: op
